public class TriggerCaseHandler {
    public static void changeDescription(List<Case> casesToBeUpdated, Map<ID, Case> oldMapCases) {
        //for (Case oneCase : casesToBeUpdated) {
         //   if (oneCase.Description == oldMapCases.get('oneCase.ID').Description) {
           //     oneCase.Description = 'My ID is: '+ oneCase.ID;
           // } else {
            //    System.debug('It was different.');
            //}
            
        //}
    }
}