public class WorkflowUtils { 
    
    public List<String> rules_x;
    public List<String> rules_y;
    
    public WorkflowUtils() {
        rules_y = new List<String>();
        rules_y.add('<fullName>Claims - Assault_Cash_Death Main Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - Assault_Cash_Death Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - Assault_Cash_Death Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - Auto Rental Insurance ENG</fullName>');
        rules_y.add('<fullName>Claims - Auto Rental Insurance Main Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - Auto Rental Insurance Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - Auto Rental Insurance Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - Auto Rental Insurance POR</fullName>');
        rules_y.add('<fullName>Claims - Auto Rental Insurance SPA</fullName>');
        rules_y.add('<fullName>Claims - Baggage Delay ENG</fullName>');
        rules_y.add('<fullName>Claims - Baggage Delay Main Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - Baggage Delay Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - Baggage Delay Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - Baggage Delay POR</fullName>');
        rules_y.add('<fullName>Claims - Baggage Delay SPA</fullName>');
        rules_y.add('<fullName>Claims - Baggage Loss ENG</fullName>');
        rules_y.add('<fullName>Claims - Baggage Loss Main Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - Baggage Loss Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - Baggage Loss Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - Baggage Loss POR</fullName>');
        rules_y.add('<fullName>Claims - Baggage Loss SPA</fullName>');
        rules_y.add('<fullName>Claims - Corporate Liability Waiver ENG</fullName>');
        rules_y.add('<fullName>Claims - Corporate Liability Waiver Main Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - Corporate Liability Waiver Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - Corporate Liability Waiver Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - Corporate Liability Waiver POR</fullName>');
        rules_y.add('<fullName>Claims - Corporate Liability Waiver SPA</fullName>');
        rules_y.add('<fullName>Claims - Extended Warranty ENG</fullName>');
        rules_y.add('<fullName>Claims - Extended Warranty Main Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - Extended Warranty Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - Extended Warranty Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - Extended Warranty POR</fullName>');
        rules_y.add('<fullName>Claims - Extended Warranty SPA</fullName>');
        rules_y.add('<fullName>Claims - IEMS ENG</fullName>');
        rules_y.add('<fullName>Claims - IEMS Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - IEMS Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - IEMS POR</fullName>');
        rules_y.add('<fullName>Claims - IEMS Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - IEMS SPA</fullName>');
        rules_y.add('<fullName>Claims - Injured Journay Accidental D%26D  Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - Injured Journay Accidental D%26D ENG</fullName>');
        rules_y.add('<fullName>Claims - Injured Journay Accidental D%26D Main Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - Injured Journay Accidental D%26D Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - Injured Journay Accidental D%26D POR</fullName>');
        rules_y.add('<fullName>Claims - Injured Journay Accidental D%26D SPA</fullName>');
        rules_y.add('<fullName>Claims - Missed Connection ENG</fullName>');
        rules_y.add('<fullName>Claims - Missed Connection Main Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - Missed Connection Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - Missed Connection Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - Missed Connection POR</fullName>');
        rules_y.add('<fullName>Claims - Missed Connection SPA</fullName>');
        rules_y.add('<fullName>Claims - Price Proteccion ENG</fullName>');
        rules_y.add('<fullName>Claims - Price Proteccion Main Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - Price Proteccion Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - Price Proteccion Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - Price Proteccion POR</fullName>');
        rules_y.add('<fullName>Claims - Price Proteccion SPA</fullName>');
        rules_y.add('<fullName>Claims - Purchase Protection ENG</fullName>');
        rules_y.add('<fullName>Claims - Purchase Protection Main Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - Purchase Protection Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - Purchase Protection Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - Purchase Protection POR</fullName>');
        rules_y.add('<fullName>Claims - Purchase Protection SPA</fullName>');
        rules_y.add('<fullName>Claims - Travel Accident Insurance Death Main Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - Travel Accident Insurance Death Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - Travel Accident Insurance Death Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - Travel Accident Insurance Dismemberment Main Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - Travel Accident Insurance Dismemberment Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - Travel Accident Insurance Dismemberment Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - Travel Accident Insurance ENG</fullName>');
        rules_y.add('<fullName>Claims - Travel Accident Insurance Main Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - Travel Accident Insurance Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - Travel Accident Insurance Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - Travel Accident Insurance POR</fullName>');
        rules_y.add('<fullName>Claims - Travel Accident Insurance SPA</fullName>');
        rules_y.add('<fullName>Claims - Trip Cancellation ENG</fullName>');
        rules_y.add('<fullName>Claims - Trip Cancellation Main Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - Trip Cancellation Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - Trip Cancellation Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - Trip Cancellation POR</fullName>');
        rules_y.add('<fullName>Claims - Trip Cancellation SPA</fullName>');
        rules_y.add('<fullName>Claims - Trip Delay ENG</fullName>');
        rules_y.add('<fullName>Claims - Trip Delay Main Portal ENG</fullName>');
        rules_y.add('<fullName>Claims - Trip Delay Main Portal POR</fullName>');
        rules_y.add('<fullName>Claims - Trip Delay Main Portal SPA</fullName>');
        rules_y.add('<fullName>Claims - Trip Delay POR</fullName>');
        rules_y.add('<fullName>Claims - Trip Delay SPA</fullName>');
        
        rules_x = new List<String>();
        rules_x.add('<fullName>Claims - 30 Days without customer documentation ENG</fullName>');
        rules_x.add('<fullName>Claims - 30 Days without customer documentation ESP</fullName>');
        rules_x.add('<fullName>Claims - 30 Days without customer documentation POR</fullName>');
        rules_x.add('<fullName>Claims - 60 Days without customer documentation ENG</fullName>');
        rules_x.add('<fullName>Claims - 60 Days without customer documentation POR</fullName>');
        rules_x.add('<fullName>Claims - 60 Days without customer documentation SPA</fullName>');
        rules_x.add('<fullName>Claims - Assault_Cash_Death Main Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - Assault_Cash_Death Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - Assault_Cash_Death Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - Auto Rental Insurance ENG</fullName>');
        rules_x.add('<fullName>Claims - Auto Rental Insurance Main Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - Auto Rental Insurance Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - Auto Rental Insurance Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - Auto Rental Insurance POR</fullName>');
        rules_x.add('<fullName>Claims - Auto Rental Insurance SPA</fullName>');
        rules_x.add('<fullName>Claims - Auto Rental Insurance SPA Argentina</fullName>');
        rules_x.add('<fullName>Claims - Auto Rental Insurance SPA Argentina CTA 250k Argentina</fullName>');
        rules_x.add('<fullName>Claims - Auto Rental Insurance SPA Argentina Visa Business Argentina</fullName>');
        rules_x.add('<fullName>Claims - Auto Rental Insurance SPA Argentina Visa Corporate T%26E Argentina</fullName>');
        rules_x.add('<fullName>Claims - Auto Rental Insurance SPA Argentina Visa GLD%2FPRM Argentina</fullName>');
        rules_x.add('<fullName>Claims - Auto Rental Insurance SPA Argentina Visa Platinum Argentina Visa Platinum Argentina</fullName>');
        rules_x.add('<fullName>Claims - Auto Rental Insurance SPA Argentina Visa Signature Argentina</fullName>');
        rules_x.add('<fullName>Claims - Auto Rental Insurance SPA Colombia</fullName>');
        rules_x.add('<fullName>Claims - Baggage Delay ENG</fullName>');
        rules_x.add('<fullName>Claims - Baggage Delay Main Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - Baggage Delay Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - Baggage Delay Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - Baggage Delay POR</fullName>');
        rules_x.add('<fullName>Claims - Baggage Delay SPA</fullName>');
        rules_x.add('<fullName>Claims - Baggage Delay SPA Argentina</fullName>');
        rules_x.add('<fullName>Claims - Baggage Delay SPA Argentina Visa Signature Argentina</fullName>');
        rules_x.add('<fullName>Claims - Baggage Delay SPA Colombia</fullName>');
        rules_x.add('<fullName>Claims - Baggage Loss ENG</fullName>');
        rules_x.add('<fullName>Claims - Baggage Loss Main Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - Baggage Loss Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - Baggage Loss Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - Baggage Loss POR</fullName>');
        rules_x.add('<fullName>Claims - Baggage Loss SPA</fullName>');
        rules_x.add('<fullName>Claims - Baggage Loss SPA Argentina</fullName>');
        rules_x.add('<fullName>Claims - Baggage Loss SPA Argentina CTA 250k Argentina</fullName>');
        rules_x.add('<fullName>Claims - Baggage Loss SPA Argentina Visa Signature Argentina</fullName>');
        rules_x.add('<fullName>Claims - Baggage Loss SPA Colombia</fullName>');
        rules_x.add('<fullName>Claims - Corporate Liability Waiver ENG</fullName>');
        rules_x.add('<fullName>Claims - Corporate Liability Waiver Main Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - Corporate Liability Waiver Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - Corporate Liability Waiver Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - Corporate Liability Waiver POR</fullName>');
        rules_x.add('<fullName>Claims - Corporate Liability Waiver SPA</fullName>');
        rules_x.add('<fullName>Claims - Corporate Liability Waiver SPA Colombia</fullName>');
        rules_x.add('<fullName>Claims - Extended Warranty ENG</fullName>');
        rules_x.add('<fullName>Claims - Extended Warranty Main Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - Extended Warranty Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - Extended Warranty Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - Extended Warranty POR</fullName>');
        rules_x.add('<fullName>Claims - Extended Warranty SPA</fullName>');
        rules_x.add('<fullName>Claims - Extended Warranty SPA Argentina</fullName>');
        rules_x.add('<fullName>Claims - Extended Warranty SPA Argentina Visa Signature Argentina</fullName>');
        rules_x.add('<fullName>Claims - Extended Warranty SPA Colombia</fullName>');
        rules_x.add('<fullName>Claims - Generic ENG</fullName>');
        rules_x.add('<fullName>Claims - Generic POR</fullName>');
        rules_x.add('<fullName>Claims - Generic SPA</fullName>');
        rules_x.add('<fullName>Claims - Generic SPA Colombia</fullName>');
        rules_x.add('<fullName>Claims - IEMS ENG</fullName>');
        rules_x.add('<fullName>Claims - IEMS Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - IEMS Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - IEMS POR</fullName>');
        rules_x.add('<fullName>Claims - IEMS Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - IEMS SPA</fullName>');
        rules_x.add('<fullName>Claims - Injured Journay Accidental D%26D  Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - Injured Journay Accidental D%26D ENG</fullName>');
        rules_x.add('<fullName>Claims - Injured Journay Accidental D%26D Main Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - Injured Journay Accidental D%26D Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - Injured Journay Accidental D%26D POR</fullName>');
        rules_x.add('<fullName>Claims - Injured Journay Accidental D%26D SPA</fullName>');
        rules_x.add('<fullName>Claims - Injured Journay Accidental D%26D SPA ARGENTINA</fullName>');
        rules_x.add('<fullName>Claims - Injured Journay Accidental D%26D SPA Colombia</fullName>');
        rules_x.add('<fullName>Claims - Injured Journay Accidental D%26D SPA Visa GLD%2FPRM Argentina</fullName>');
        rules_x.add('<fullName>Claims - Injured Journay Accidental D%26D SPA Visa Signature Argentina</fullName>');
        rules_x.add('<fullName>Claims - Legal Fees ENG</fullName>');
        rules_x.add('<fullName>Claims - Legal Fees POR</fullName>');
        rules_x.add('<fullName>Claims - Legal Fees SPA</fullName>');
        rules_x.add('<fullName>Claims - Legal Fees SPA Colombia</fullName>');
        rules_x.add('<fullName>Claims - Missed Connection ENG</fullName>');
        rules_x.add('<fullName>Claims - Missed Connection Main Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - Missed Connection Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - Missed Connection Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - Missed Connection POR</fullName>');
        rules_x.add('<fullName>Claims - Missed Connection SPA</fullName>');
        rules_x.add('<fullName>Claims - Missed Connection SPA Colombia</fullName>');
        rules_x.add('<fullName>Claims - Other ENG</fullName>');
        rules_x.add('<fullName>Claims - Other POR</fullName>');
        rules_x.add('<fullName>Claims - Other SPA</fullName>');
        rules_x.add('<fullName>Claims - Price Proteccion ENG</fullName>');
        rules_x.add('<fullName>Claims - Price Proteccion Main Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - Price Proteccion Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - Price Proteccion Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - Price Proteccion POR</fullName>');
        rules_x.add('<fullName>Claims - Price Proteccion SPA</fullName>');
        rules_x.add('<fullName>Claims - Price Proteccion SPA Argentina</fullName>');
        rules_x.add('<fullName>Claims - Price Proteccion SPA Argentina Visa Signature Argentina</fullName>');
        rules_x.add('<fullName>Claims - Price Proteccion SPA Colombia</fullName>');
        rules_x.add('<fullName>Claims - Purchase Protection ENG</fullName>');
        rules_x.add('<fullName>Claims - Purchase Protection Main Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - Purchase Protection Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - Purchase Protection Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - Purchase Protection POR</fullName>');
        rules_x.add('<fullName>Claims - Purchase Protection SPA</fullName>');
        rules_x.add('<fullName>Claims - Purchase Protection SPA ARGENTINA</fullName>');
        rules_x.add('<fullName>Claims - Purchase Protection SPA Colombia</fullName>');
        rules_x.add('<fullName>Claims - Purchase Protection SPA Visa Platinum Argentina</fullName>');
        rules_x.add('<fullName>Claims - Purchase Protection SPA Visa Signature Argentina</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance Death Main Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance Death Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance Death Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance Dismemberment Main Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance Dismemberment Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance Dismemberment Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance ENG</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance Main Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance POR</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance SPA</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance SPA Argentina</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance SPA Argentina CTA 250k Argentina</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance SPA Argentina Visa Business Argentina</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance SPA Argentina Visa Classic Argentina</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance SPA Argentina Visa Corporate T%26E Argentina</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance SPA Argentina Visa Platinum Argentina</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance SPA Argentina Visa Signature Argentina</fullName>');
        rules_x.add('<fullName>Claims - Travel Accident Insurance SPA Colombia</fullName>');
        rules_x.add('<fullName>Claims - Trip Cancellation ENG</fullName>');
        rules_x.add('<fullName>Claims - Trip Cancellation Main Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - Trip Cancellation Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - Trip Cancellation Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - Trip Cancellation POR</fullName>');
        rules_x.add('<fullName>Claims - Trip Cancellation SPA</fullName>');
        rules_x.add('<fullName>Claims - Trip Cancellation SPA Colombia</fullName>');
        rules_x.add('<fullName>Claims - Trip Delay ENG</fullName>');
        rules_x.add('<fullName>Claims - Trip Delay Main Portal ENG</fullName>');
        rules_x.add('<fullName>Claims - Trip Delay Main Portal POR</fullName>');
        rules_x.add('<fullName>Claims - Trip Delay Main Portal SPA</fullName>');
        rules_x.add('<fullName>Claims - Trip Delay POR</fullName>');
        rules_x.add('<fullName>Claims - Trip Delay SPA</fullName>');
        rules_x.add('<fullName>Claims - Trip Delay SPA Colombia</fullName>');
        
    }
    
    
    public List<String> isContained() {
        System.debug('List size: ' + rules_y.size());
        List<String> itensEncontrados = new List<String>();
        
        for (String item : rules_y) {
            if (rules_x.contains(item)) {
                itensEncontrados.add(item);
            }
        }
        System.debug('itensEncontrados size: ' + itensEncontrados.size());
        return itensEncontrados;
    }
    
    public Map<String, Integer> repeatedItems() {
        Map<String, Integer> itensDaLista = new Map<String, Integer>();
        Map<String, Integer> itensRepetidos = new Map<String, Integer>();
        for (Integer i = 0; i < rules_y.size(); i++) {
			for (Integer j = 0; j < rules_x.size(); j++) {
                if (rules_y[i] == rules_x[j]) {
                    // item não existir no map, inserir e inicializar o cont em 1
                    if (itensDaLista.get(rules_y[i]) == null) {
                        itensDaLista.put(rules_y[i], 1);
                    } else if (itensDaLista.get(rules_y[i]) != null) {
                        itensDaLista.put(rules_y[i], itensDaLista.get(rules_y[i]) + 1);
                        itensRepetidos.put(rules_y[i], itensDaLista.get(rules_y[i]));
                    }
                }
        	}   
        }
        return itensRepetidos;
    }
    
    public List<String> leftOversFromX() {
        List<String> leftOvers = new List<String>();
        for (String item : rules_x) {
            if (!rules_y.contains(item)) {
                leftOvers.add(item);
            }
        }
        return leftOvers;
    }
   
}